
package com.calculadora.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculadora", targetNamespace = "http://ws.calculadora.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculadora {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operacion", targetNamespace = "http://ws.calculadora.com/", className = "com.calculadora.ws.Operacion")
    @ResponseWrapper(localName = "operacionResponse", targetNamespace = "http://ws.calculadora.com/", className = "com.calculadora.ws.OperacionResponse")
    @Action(input = "http://ws.calculadora.com/Calculadora/operacionRequest", output = "http://ws.calculadora.com/Calculadora/operacionResponse")
    public double operacion(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
